### ISSUE TITLE
Release a version with fixed return type of runCommand()

### ISSUE THREAD

**Issue by mirao** [thiagodp/codeceptjs-cmdhelper#16]
@thiagodp 
I noticed that you've already fixed it in https://github.com/thiagodp/codeceptjs-cmdhelper/commit/ff68c0e30d432687c30926b82a0868cf9c13b999 , but it was not released yet.
Could you release it? Thanks.

I'm reporting it because I noticed in my TS code that inferring of type for a variable populated by `I.runCommand()` gives me `any` instead of `number`

**Comment by thiagodp** [comment]
Hello, @mirao ! It was just released in `2.4.1`. Thank you.

**Comment by mirao** [comment]
Thanks!
